name: maps_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  animated_rail: ^2.0.2
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  

flutter:
  uses-material-design: true
